2022-05-23 13:08:40,685 [INFO] start (ws_async_manager.py:54): [连接管理]程序启动...
2022-05-23 13:08:40,686 [INFO] run (ws_async_pool.py:34): [连接池]最大并发连接数: 1, 启动会话数: 1
2022-05-23 13:08:40,686 [INFO] new_connect (ws_async_manager.py:110): [连接管理]新会话启动中...
2022-05-23 13:08:40,686 [INFO] connect (ws_async_client.py:79): [ws连接]启动中...
2022-05-23 13:08:40,836 [INFO] identify (ws_async_client.py:113): [ws连接]鉴权中...
2022-05-23 13:08:40,837 [INFO] _send_heartbeat (ws_async_client.py:193): [ws连接]心跳检测启动...
2022-05-23 13:08:40,967 [INFO] on_message (ws_async_client.py:57): [ws连接]鉴权成功
2022-05-23 13:08:40,968 [INFO] on_message (ws_async_client.py:62): [ws连接]程序启动成功！
2022-05-23 13:08:46,437 [INFO] start_session (ws_async_manager.py:98): [连接管理]服务强行停止!
2022-05-23 13:14:13,125 [INFO] start (ws_async_manager.py:54): [连接管理]程序启动...
2022-05-23 13:14:13,127 [INFO] run (ws_async_pool.py:34): [连接池]最大并发连接数: 1, 启动会话数: 1
2022-05-23 13:14:13,127 [INFO] new_connect (ws_async_manager.py:110): [连接管理]新会话启动中...
2022-05-23 13:14:13,127 [INFO] connect (ws_async_client.py:79): [ws连接]启动中...
2022-05-23 13:14:13,302 [INFO] identify (ws_async_client.py:113): [ws连接]鉴权中...
2022-05-23 13:14:13,303 [INFO] _send_heartbeat (ws_async_client.py:193): [ws连接]心跳检测启动...
2022-05-23 13:14:13,428 [INFO] on_message (ws_async_client.py:57): [ws连接]鉴权成功
2022-05-23 13:14:13,428 [INFO] on_message (ws_async_client.py:62): [ws连接]程序启动成功！
2022-05-23 13:17:21,551 [INFO] start_session (ws_async_manager.py:98): [连接管理]服务强行停止!
2022-05-23 13:17:23,203 [INFO] start (ws_async_manager.py:54): [连接管理]程序启动...
2022-05-23 13:17:23,204 [INFO] run (ws_async_pool.py:34): [连接池]最大并发连接数: 1, 启动会话数: 1
2022-05-23 13:17:23,205 [INFO] new_connect (ws_async_manager.py:110): [连接管理]新会话启动中...
2022-05-23 13:17:23,205 [INFO] connect (ws_async_client.py:79): [ws连接]启动中...
2022-05-23 13:17:23,334 [INFO] identify (ws_async_client.py:113): [ws连接]鉴权中...
2022-05-23 13:17:23,335 [INFO] _send_heartbeat (ws_async_client.py:193): [ws连接]心跳检测启动...
2022-05-23 13:17:23,411 [INFO] on_message (ws_async_client.py:57): [ws连接]鉴权成功
2022-05-23 13:17:23,411 [INFO] on_message (ws_async_client.py:62): [ws连接]程序启动成功！
2022-05-23 13:17:33,724 [ERROR] _handle_response (async_http.py:61): [HTTP]接口请求异常，请求连接: https://api.sgroup.qq.com/channels/6557701/messages, error: 400, 返回内容: {"message":"400: Bad Request","code":10001}, trace_id:528faaa5f52d81b37b3868b3daf335c4
2022-05-23 13:18:17,872 [ERROR] _handle_response (async_http.py:61): [HTTP]接口请求异常，请求连接: https://api.sgroup.qq.com/channels/6557701/messages, error: 400, 返回内容: {"message":"400: Bad Request","code":10001}, trace_id:cb68d66bfdaa71c48a05b831aabd2aa9
2022-05-23 13:19:13,818 [INFO] start_session (ws_async_manager.py:98): [连接管理]服务强行停止!
2022-05-23 13:19:15,919 [INFO] start (ws_async_manager.py:54): [连接管理]程序启动...
2022-05-23 13:19:15,920 [INFO] run (ws_async_pool.py:34): [连接池]最大并发连接数: 1, 启动会话数: 1
2022-05-23 13:19:15,921 [INFO] new_connect (ws_async_manager.py:110): [连接管理]新会话启动中...
2022-05-23 13:19:15,921 [INFO] connect (ws_async_client.py:79): [ws连接]启动中...
2022-05-23 13:19:16,068 [INFO] identify (ws_async_client.py:113): [ws连接]鉴权中...
2022-05-23 13:19:16,068 [INFO] _send_heartbeat (ws_async_client.py:193): [ws连接]心跳检测启动...
2022-05-23 13:19:16,174 [INFO] on_message (ws_async_client.py:57): [ws连接]鉴权成功
2022-05-23 13:19:16,174 [INFO] on_message (ws_async_client.py:62): [ws连接]程序启动成功！
2022-05-23 13:19:24,541 [ERROR] _handle_response (async_http.py:61): [HTTP]接口请求异常，请求连接: https://api.sgroup.qq.com/channels/6557701/messages, error: 400, 返回内容: {"message":"400: Bad Request","code":10001}, trace_id:25abbd9029e3c9b6836fb9f54af1053a
2022-05-23 13:22:11,791 [INFO] start_session (ws_async_manager.py:98): [连接管理]服务强行停止!
2022-05-23 13:22:14,187 [INFO] start (ws_async_manager.py:54): [连接管理]程序启动...
2022-05-23 13:22:14,191 [INFO] run (ws_async_pool.py:34): [连接池]最大并发连接数: 1, 启动会话数: 1
2022-05-23 13:22:14,192 [INFO] new_connect (ws_async_manager.py:110): [连接管理]新会话启动中...
2022-05-23 13:22:14,192 [INFO] connect (ws_async_client.py:79): [ws连接]启动中...
2022-05-23 13:22:14,363 [INFO] identify (ws_async_client.py:113): [ws连接]鉴权中...
2022-05-23 13:22:14,364 [INFO] _send_heartbeat (ws_async_client.py:193): [ws连接]心跳检测启动...
2022-05-23 13:22:14,483 [INFO] on_message (ws_async_client.py:57): [ws连接]鉴权成功
2022-05-23 13:22:14,484 [INFO] on_message (ws_async_client.py:62): [ws连接]程序启动成功！
2022-05-23 13:22:59,351 [ERROR] _handle_response (async_http.py:61): [HTTP]接口请求异常，请求连接: https://api.sgroup.qq.com/dms/1007206365482934096/messages, error: 500, 返回内容: {"code":304049,"message":"push dm message reach limit"}, trace_id:19a6233dbb69d32ce4fee6f1336aad1a
2022-05-23 13:32:39,101 [INFO] start_session (ws_async_manager.py:98): [连接管理]服务强行停止!
2022-05-23 13:32:40,584 [INFO] start (ws_async_manager.py:54): [连接管理]程序启动...
2022-05-23 13:32:40,585 [INFO] run (ws_async_pool.py:34): [连接池]最大并发连接数: 1, 启动会话数: 1
2022-05-23 13:32:40,585 [INFO] new_connect (ws_async_manager.py:110): [连接管理]新会话启动中...
2022-05-23 13:32:40,585 [INFO] connect (ws_async_client.py:79): [ws连接]启动中...
2022-05-23 13:32:40,722 [INFO] identify (ws_async_client.py:113): [ws连接]鉴权中...
2022-05-23 13:32:40,723 [INFO] _send_heartbeat (ws_async_client.py:193): [ws连接]心跳检测启动...
2022-05-23 13:32:40,811 [INFO] on_message (ws_async_client.py:57): [ws连接]鉴权成功
2022-05-23 13:32:40,812 [INFO] on_message (ws_async_client.py:62): [ws连接]程序启动成功！
2022-05-23 13:33:58,476 [INFO] start_session (ws_async_manager.py:98): [连接管理]服务强行停止!
2022-05-23 13:34:00,365 [INFO] start (ws_async_manager.py:54): [连接管理]程序启动...
2022-05-23 13:34:00,367 [INFO] run (ws_async_pool.py:34): [连接池]最大并发连接数: 1, 启动会话数: 1
2022-05-23 13:34:00,367 [INFO] new_connect (ws_async_manager.py:110): [连接管理]新会话启动中...
2022-05-23 13:34:00,367 [INFO] connect (ws_async_client.py:79): [ws连接]启动中...
2022-05-23 13:34:00,521 [INFO] identify (ws_async_client.py:113): [ws连接]鉴权中...
2022-05-23 13:34:00,522 [INFO] _send_heartbeat (ws_async_client.py:193): [ws连接]心跳检测启动...
2022-05-23 13:34:00,647 [INFO] on_message (ws_async_client.py:57): [ws连接]鉴权成功
2022-05-23 13:34:00,647 [INFO] on_message (ws_async_client.py:62): [ws连接]程序启动成功！
2022-05-23 13:34:31,394 [ERROR] _handle_response (async_http.py:61): [HTTP]接口请求异常，请求连接: https://api.sgroup.qq.com/dms/1007206365482934096/messages, error: 500, 返回内容: {"code":304049,"message":"push dm message reach limit"}, trace_id:f834535756bae3d91abd70a17f062285
2022-05-23 13:34:49,441 [INFO] start_session (ws_async_manager.py:98): [连接管理]服务强行停止!
2022-05-23 13:44:52,138 [INFO] start (ws_async_manager.py:54): [连接管理]程序启动...
2022-05-23 13:44:52,139 [INFO] run (ws_async_pool.py:34): [连接池]最大并发连接数: 1, 启动会话数: 1
2022-05-23 13:44:52,140 [INFO] new_connect (ws_async_manager.py:110): [连接管理]新会话启动中...
2022-05-23 13:44:52,140 [INFO] connect (ws_async_client.py:79): [ws连接]启动中...
2022-05-23 13:44:52,287 [INFO] identify (ws_async_client.py:113): [ws连接]鉴权中...
2022-05-23 13:44:52,288 [INFO] _send_heartbeat (ws_async_client.py:193): [ws连接]心跳检测启动...
2022-05-23 13:44:52,421 [INFO] on_message (ws_async_client.py:57): [ws连接]鉴权成功
2022-05-23 13:44:52,421 [INFO] on_message (ws_async_client.py:62): [ws连接]程序启动成功！
2022-05-23 13:47:01,134 [INFO] start_session (ws_async_manager.py:98): [连接管理]服务强行停止!
